name: Smoke Tests - PR

on:
  pull_request:
    branches: [master]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto
        uses: actions/checkout@v4

      # instalar java
      - name: instalar java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'

      # instalar chrome
      - name: instalar chrome
        uses: browser-actions/setup-chrome@v1

      # instalar chrome driver
      - name: instalar chrome Driver
        uses: nanasess/setup-chromedriver@v2
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      # executar os testes
      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci
